# -*- coding: utf-8 -*-
"""Inc5000 Company List_2014.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKxF8dw8AXREoa6J8L-QdL5unMajZXbg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

df = pd.read_csv("Data Set- Inc5000 Company List_2014.csv")

df.head()

df.info()

"""### Observation

- The dataset contains 5,000 company records with 13 columns.
- It includes both numerical and categorical features.
- The dataset is complete with no missing values after the data cleaning process.
- The data types are appropriate for analysis.
"""

df.describe()

"""### Observation

- Revenue and employee counts vary significantly across companies.
- Growth percentages show a wide range, indicating different business growth patterns.
- The large difference between minimum and maximum values suggests the presence of high-value companies and possible outliers.
"""

df.isnull().sum()

df.tail()

df.sample(5)

df.shape

df["industry"].value_counts()

top10 = df.sort_values("revenue_usd", ascending=False).head(10)

top10[["company", "revenue_usd"]]

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


plt.figure(figsize=(8,5))
plt.hist(df["revenue_usd"], bins=30)
plt.title("Revenue Distribution")
plt.xlabel("Revenue")
plt.ylabel("Frequency")
plt.show()

"""### Observation

- The revenue distribution is right-skewed.
- Most companies generate relatively lower revenue.
- Only a small number of companies generate extremely high revenue.
"""

plt.figure(figsize=(8,5))
plt.hist(df["growth_percent"], bins=30)
plt.title("Growth Distribution")
plt.xlabel("Growth (%)")
plt.ylabel("Frequency")
plt.show()

"""### Observation

- Most companies have moderate growth rates.
- A few companies exhibit exceptionally high growth.
- High-growth companies appear as outliers in the distribution.
"""

plt.figure(figsize=(14,6))

top_industries = df["industry"].value_counts().head(10)

top_industries.plot(kind="bar")

plt.title("Top 10 Industries")
plt.xlabel("Industry")
plt.ylabel("Number of Companies")

plt.xticks(rotation=45, ha='right')

plt.tight_layout()

plt.show()

"""### Observation

- IT Services has the highest number of companies.
- Advertising & Marketing and Software are also among the most represented industries.
- Technology-related industries dominate the dataset.
"""

top_states = df["state"].value_counts().head(10)

plt.figure(figsize=(10,6))
top_states.plot(kind="bar")
plt.title("Top 10 States")
plt.xlabel("State")
plt.ylabel("Number of Companies")
plt.xticks(rotation=45)
plt.show()

"""### Observation

- A small number of states contain the majority of companies.
- Business activity is concentrated in economically developed regions.
"""

plt.figure(figsize=(8,6))
plt.scatter(df["employee_count"], df["revenue_usd"])
plt.title("Revenue vs Employee Count")
plt.xlabel("Employee Count")
plt.ylabel("Revenue")
plt.show()

"""### Observation

- There is a positive relationship between employee count and revenue.
- Companies with more employees generally report higher revenue.
- Some companies generate high revenue despite having relatively few employees.
"""

plt.figure(figsize=(10,6))

df.groupby('industry')['revenue_usd'].mean().sort_values().tail(10).plot(kind='barh')

plt.title("Top 10 Industries by Average Revenue")
plt.xlabel("Average Revenue (USD)")
plt.ylabel("Industry")

plt.tight_layout()
plt.show()

"""### Observation

- Average revenue differs across industries.
- Some industries with fewer companies generate higher average revenue.
- Revenue performance is influenced by industry type.
"""

df.corr(numeric_only=True)

import seaborn as sns

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="Blues")
plt.title("Correlation Matrix")
plt.show()

"""### Observation

- Employee count shows a positive correlation with revenue.
- Growth percentage has a relatively weak relationship with other numerical variables.
- No extremely strong correlations are observed among the remaining variables.

# Business Insights

1. IT Services is the most represented industry among Inc. 5000 companies.

2. Technology-related industries account for a large share of high-growth businesses.

3. Company revenue is unevenly distributed, with a few organizations contributing a significant portion of total revenue.

4. Business activity is concentrated in a limited number of states, highlighting regional economic hubs.

5. Companies with larger employee counts generally generate higher revenue.

6. Some industries have fewer companies but achieve higher average revenue, indicating stronger earning potential.

7. Exceptional growth is limited to a relatively small number of companies.

8. Company performance is influenced by multiple factors, including industry, workforce size, and geographic location.

# Conclusion

This exploratory data analysis examined the Inc. 5000 company dataset to understand trends in revenue, growth, industry distribution, workforce size, and geographic presence.

The analysis found that technology-related industries, particularly IT Services, have the highest representation among high-growth companies. Revenue is highly concentrated among a small number of organizations, while employee count generally shows a positive relationship with revenue. Business activity is also concentrated in a few states, suggesting the importance of regional business ecosystems.

Overall, the analysis provides valuable insights into the characteristics of successful, high-growth companies and demonstrates how data can support strategic business decisions related to investment, expansion, and market analysis.
"""